<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

#[Fillable([
    'orden_servicio_id',
    'cotizacion_id',
    'cliente_id',
    'partner_id',
    'tipo',
    'categoria',
    'monto',
    'descripcion',
    'fecha',
    'external_id',
    'movimiento_original_id',
    'motivo_reversion',
    'revertido_por_user_id',
])]
class MovimientoFinanciero extends Model
{
    protected $table = 'movimientos_financieros';

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'monto' => 'decimal:2',
            'fecha' => 'date',
        ];
    }

    /**
     * Get the service order assigned to this financial movement.
     */
    public function ordenServicio(): BelongsTo
    {
        return $this->belongsTo(OrdenServicio::class);
    }

    /**
     * Get the quote that originated the financial movement.
     */
    public function cotizacion(): BelongsTo
    {
        return $this->belongsTo(Cotizacion::class);
    }

    /**
     * Get the client assigned to this financial movement.
     */
    public function cliente(): BelongsTo
    {
        return $this->belongsTo(Cliente::class);
    }

    /**
     * Get the partner assigned to this financial movement.
     */
    public function partner(): BelongsTo
    {
        return $this->belongsTo(Partner::class);
    }

    /**
     * The movement this one reverses, when this row is itself a reversion.
     */
    public function movimientoOriginal(): BelongsTo
    {
        return $this->belongsTo(self::class, 'movimiento_original_id');
    }

    /**
     * The compensating reversion movement, when this row has been reverted.
     */
    public function movimientoReversion(): HasOne
    {
        return $this->hasOne(self::class, 'movimiento_original_id');
    }

    public function revertidoPor(): BelongsTo
    {
        return $this->belongsTo(User::class, 'revertido_por_user_id');
    }

    /**
     * True when this row is itself a compensating reversion, not an original.
     */
    public function esReversion(): bool
    {
        return $this->movimiento_original_id !== null;
    }

    /**
     * Structured movements are generated by GenerarFinanzasOrdenServicio or
     * RegistrarAnticipoCotizacion, never manually. Both always anchor the row
     * to an order and/or a quote, so that link is the safe, structural signal
     * -- never the free-text categoria/descripcion.
     */
    public function esEstructurado(): bool
    {
        return $this->orden_servicio_id !== null || $this->cotizacion_id !== null;
    }
}
