<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

#[Fillable([
    'folio',
    'cliente_id',
    'equipo_id',
    'creado_por_user_id',
    'partner_recepcion_id',
    'partner_tecnico_id',
    'tipo_recepcion',
    'estado',
    'total_cliente',
    'costo_tecnico',
    'comision_logistica',
    'utilidad_neta',
    'notas',
    'fecha_recepcion',
    'fecha_entrega',
    'finanzas_generadas',
])]
class OrdenServicio extends Model
{
    protected $table = 'ordenes_servicio';

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'total_cliente' => 'decimal:2',
            'costo_tecnico' => 'decimal:2',
            'comision_logistica' => 'decimal:2',
            'utilidad_neta' => 'decimal:2',
            'fecha_recepcion' => 'datetime',
            'fecha_entrega' => 'datetime',
            'finanzas_generadas' => 'boolean',
        ];
    }

    /**
     * Get the client assigned to the service order.
     */
    public function cliente(): BelongsTo
    {
        return $this->belongsTo(Cliente::class);
    }

    /**
     * Get the equipment assigned to the service order.
     */
    public function equipo(): BelongsTo
    {
        return $this->belongsTo(Equipo::class);
    }

    /**
     * Get the user that created the service order.
     */
    public function creadoPor(): BelongsTo
    {
        return $this->belongsTo(User::class, 'creado_por_user_id');
    }

    /**
     * Get the reception partner assigned to the service order.
     */
    public function partnerRecepcion(): BelongsTo
    {
        return $this->belongsTo(Partner::class, 'partner_recepcion_id');
    }

    /**
     * Get the technical partner assigned to the service order.
     */
    public function partnerTecnico(): BelongsTo
    {
        return $this->belongsTo(Partner::class, 'partner_tecnico_id');
    }

    /**
     * Get the service details for the order.
     */
    public function detalles(): HasMany
    {
        return $this->hasMany(OrdenServicioDetalle::class);
    }

    /**
     * Get the parts used for the order.
     */
    public function refacciones(): HasMany
    {
        return $this->hasMany(OrdenServicioRefaccion::class);
    }

    /**
     * Get the status history for the order.
     */
    public function historialEstados(): HasMany
    {
        return $this->hasMany(HistorialEstado::class);
    }

    /**
     * Get the financial movements generated by the service order.
     */
    public function movimientosFinancieros(): HasMany
    {
        return $this->hasMany(MovimientoFinanciero::class);
    }
}
